App_Login/urls.py
from django.urls import path

from App_Login import views

app_name = 'App_Login'

urlpatterns = [
     path('register/', views.register, name='register'),
     path('login/', views.login_page, name='login'),
     path('profile/', views.home, name='profile'),
     path('logout/', views.logout_user, name='logout'),
]

Product_App/urls.py
from django.urls import path

from Product_App import views

app_name = 'Product_App'

urlpatterns = [
    path('', views.index, name='index'),
    path('reservation/<int:id>', views.reservation, name='reservation'),
    path('ur_reserve/', views.ur_reserve, name='ur_reserve'),
    path('menus/<int:id>', views.menu_list, name='menus'),
    path('orders/', views.orders, name='orders'),

    # Cart
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/<int:id>', views.cart_detail, name='cart_detail'),
]

Restaurent_App/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from App_Login import views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('account/', include('App_Login.urls')),
    path('product/', include('Product_App.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Product_App/models.py
from tkinter.ttk import Widget
from django.db import models
from django.contrib.auth.models import User
from django.forms import DateInput

# Create your models here.


class Restaurent(models.Model):
    name = models.CharField(max_length=40)
    restaurent_pics = models.ImageField(upload_to = 'restaurent_pics', blank=True)
    total_seat = models.IntegerField()
    opening = models.CharField(max_length=10)
    closed = models.CharField(max_length=10)

    def __str__(self):
        return f'{self.name}'

TIME_CHOICES =(
    ("10", "10:00 AM"),
    ("11", "11:00 AM"),
    ("12", "12:00 PM"),
    ("1", "1:00 PM"),
    ("2", "2:00 PM"),

)

STATUS_CHOICES =(
    ("Pending", "Pending"),
    ("Accepted", "Accepted"),
    ("Rejected", "Rejected"),
    ("Restore", "Restore"),

)
class Reservation(models.Model):
    restaurents = models.ForeignKey(Restaurent, on_delete=models.CASCADE, null=False, default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    person = models.IntegerField(default='1')
    booking_date = models.DateField(null=True)
    booking_time = models.CharField(choices=TIME_CHOICES, max_length=50, null=True)
    status = models.CharField(max_length=40,choices=STATUS_CHOICES,default='Pending')

    def __str__(self):
        return f'{self.restaurents.name} status {self.status}'

class Product(models.Model):
    restaurents = models.ForeignKey(Restaurent, on_delete=models.CASCADE, null=False, default='')
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='product_images')
    price = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    image = models.ImageField(upload_to="product_images")
    product_name = models.CharField(max_length=50, null=True)
    product_id = models.CharField(max_length=50, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.CharField(max_length=1000, default="")
    quantity = models.CharField(max_length=50, null=True)
    total = models.CharField(max_length=50, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product_name

class History(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    restaurent_id = models.CharField(max_length=100, null=True)
    product_id = models.CharField(max_length=50, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.order.product_name

Product_App/forms.py
from django import forms
from Product_App.models import Reservation
import datetime


class ReserveForm(forms.ModelForm):

    def __init__(self, restaurent_seat, *args, **kwargs):
        self.restaurent_seat = restaurent_seat
        super(ReserveForm, self).__init__(*args, **kwargs)

    booking_date = forms.DateField(widget=forms.DateInput(attrs=dict(type='date')))
    restaurents = forms.HiddenInput()
    class Meta:
        model = Reservation
        fields = ('person', 'booking_date', 'booking_time')
        widgets = {
            'restaurents': forms.HiddenInput(),
        }

    def clean_booking_date(self):
        date = self.cleaned_data.get('booking_date')
        if date < datetime.date.today():
            raise forms.ValidationError("The date cannot be in the past!")
        return date

    def clean_person(self):
        rest = self.restaurent_seat
        persons = self.cleaned_data.get('person')
        # print(rest.total_seat)
        if persons>rest:
            raise forms.ValidationError(f"Restaurent Capacity {rest}")
        return persons

Product_App/views.py
from itertools import product
from django.urls import reverse
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from cart.cart import Cart

from Product_App.models import Product



from Product_App.forms import ReserveForm

from .models import History, Order, Reservation, Restaurent

# Create your views here.

def index(request):
    restaurent = Restaurent.objects.all()
    return render(request,'Product_App/index.html', {'values':restaurent})


def reservation(request,id):
    queryset = Restaurent.objects.filter(pk=id)
    restaurent = get_object_or_404(queryset, pk=id)

    #Getting specific restaurent seat capacity
    for seat in queryset:
        restaurent_seat=seat.total_seat

   #Passes into the ReserveForm to make error
    form = ReserveForm(restaurent_seat=restaurent_seat)

    if request.method == 'POST':
            form = ReserveForm(restaurent_seat = restaurent_seat,data=request.POST)
            if form.is_valid():
                reserved = form.save(commit=False)
                reserved.user = request.user
                reserved.restaurents = restaurent
                reserved.save()
                messages.success(request, "Request for reservation successfull. Wait Please!")
                return HttpResponseRedirect(reverse('Product_App:index'))
                
    return render(request, 'Product_App/reservation.html', {'form':form, 'restaurent':queryset})

def ur_reserve(request):
    table = Reservation.objects.filter(user=request.user)
    return render(request, 'Product_App/your_reserve.html', {'table':table})

def orders(request):
    if request.method == 'POST':
        extra_charge = request.POST.get('service')
        rest_id = request.POST.get('rest_id')

        cart = request.session.get('cart')
        sum = 0
        for key_1, value_1 in cart.items():
            val = value_1['restaurent_id']
            val = value_1['restaurent_id']
            price = value_1['price']
            
            if int(val) == int(rest_id):
                sum = sum+int(price)

        for key, value in cart.items():
            val = value['restaurent_id']
            total = int(value['quantity'])*int(value['price'])


            if int(val) == int(rest_id):
                if extra_charge == 'waiter':
                    order = Order(
                        image = value['image'],
                        product_name= value['name'],
                        product_id= value['product_id'],
                        user = request.user,
                        price = value['price'],
                        quantity = value['quantity'],
                        total = total+10,
                    )
                    order.save()
                elif extra_charge == 'self':
                    order = Order(
                        image = value['image'],
                        product_name= value['name'],
                        product_id= value['product_id'],
                        user = request.user,
                        price = value['price'],
                        quantity = value['quantity'],
                        total = total,
                    )
                    order.save()

                #Order
                orders = Order.objects.last()

                history = History(
                    order = orders,
                    user = request.user,
                    product_id= value['product_id'],
                    restaurent_id = value['restaurent_id'],
                )
                history.save()
        request.session['cart'] = {}
        messages.success(request, "Order Placed Successfully")
        return redirect('Product_App:index')


    print(extra_charge, rest_id, sum)
    
    return render(request, 'Product_App/orders.html')

def menu_list(request, id):
    queryset = Restaurent.objects.filter(pk=id)
    restaurent = get_object_or_404(queryset, pk=id)
    table = Product.objects.filter(restaurents=restaurent)
    reserve_check = Reservation.objects.filter(restaurents=restaurent)
    
    for check in reserve_check:
        status = check.status
        user = check.user

    return render(request, 'Product_App/menus.html', {'table':table, 'status':status, 'user':user})



@login_required(login_url="/account/login")
def cart_add(request, id):
    cart = Cart(request)
   
    queryset = Product.objects.filter(pk=id)
    product = get_object_or_404(queryset, pk=id)
    restaurent = product.restaurents.id

    cart.add(product=product, restaurent = restaurent)
    return redirect("Product_App:menus", id=restaurent)


@login_required(login_url="/users/login")
def item_clear(request, id):

    cart = Cart(request)
    queryset = Product.objects.filter(pk=id)
    product = get_object_or_404(queryset, pk=id)
    restaurent = product.restaurents.id
    cart.remove(product)

    return redirect("Product_App:cart_detail", id=restaurent)


@login_required(login_url="/users/login")
def item_increment(request, id):
    cart = Cart(request)
    queryset = Product.objects.filter(pk=id)
    product = get_object_or_404(queryset, pk=id)
    restaurent = product.restaurents.id

    cart.add(product=product, restaurent = restaurent)
    return redirect("Product_App:cart_detail",id=restaurent)


@login_required(login_url="/users/login")
def item_decrement(request, id):
    cart = Cart(request)
    queryset = Product.objects.filter(pk=id)
    product = get_object_or_404(queryset, pk=id)
    restaurent = product.restaurents.id
    cart.decrement(product=product, restaurent=restaurent)
    return redirect("Product_App:cart_detail", id=restaurent)


@login_required(login_url="/users/login")
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("Product_App:cart_detail")


@login_required(login_url="/users/login")
def cart_detail(request, id):
    queryset = Product.objects.filter(pk=id)
    product = get_object_or_404(queryset, pk=id)
    restaurents = product.restaurents.id
    print(restaurents)
    restaurent = Restaurent.objects.filter(pk=id)

    return render(request, 'Product_App/cart/cart_detail.html', {'restaurent':restaurent})

templates/Product_App/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}



<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12">
            {% if messages %}

            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                {{message}}
            </div>
            {% endfor %}

            {% endif %}
        </div>
        {% for data in values %}
        <div class="col-md-4">
            <div class="card mt-3" style="width: 18rem;">
                <img class="card-img-top" src="/media/{{data.restaurent_pics}}" alt="Card image cap" style="width:18rem; height:15rem">
                <div class="card-body">
                  <h5 class="card-title text-center">{{data.name}}</h5>
                  <table class="table table-borderless">
                      <tr>
                          <td>Opening Time</td>
                          <td>{{data.opening}}</td>
                      </tr>
                      <tr>
                        <td>Closing Time</td>
                        <td>{{data.closed}}</td>
                      </tr>
                  </table>
                  <a href="{% url 'Product_App:reservation' id=data.id %}" class="btn btn-primary btn-block">Reserve Table</a>
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/Product_App/menus.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}



<div class="container">
    <div class="row mt-3">
        <div class="col-12">
            {% if messages %}

            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                {{message}}
            </div>
            {% endfor %}

            {% endif %}
        </div>
        {% for data in table %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="/media/{{data.image}}" alt="Card image cap"
                    style="width:18rem; height:15rem">
                <div class="card-body">
                    <h5 class="card-title text-center">{{data.name}}</h5>
                        {% if status == 'Accepted' and user == request.user %}
                        <a href="{% url 'Product_App:cart_add' data.id %}" class="btn btn-primary btn-block">Add to cart</a>
                        {% else %}
                        <table class="table table-borderless text-center">
                            <tr>
                                <td>Price</td>
                                <td>{{data.price}}</td>
                            </tr>
                        </table>
                        {%endif%}

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/Product_App/reservation.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<div class="wrap shadow">
    <div class="card">
        <div class="card-body">
            <h2 class="text-center">Reserve a Table</h2>
    
            {% for data in restaurent %}
           
               <div class="text-center">
                <img src="/media/{{data.restaurent_pics}}" alt="" style="width: 80px; margin: auto;">
                <h1>{{data.name}}</h1>
               </div>
                
      
            {% endfor %}
            <form action="" method="POST">
                {% csrf_token %}
                
                {{ form|crispy }}
                <div class="form-group">
                    <input class="btn btn-primary" type="submit" value="Request for reserve">
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

templates/Product_App/your_reserve.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="wrap-table shadow">
                <div class="card">
                    <div class="card-body">
                        <h2>Active Restaurent</h2>
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Restaurent</th>
                                    <th>Status</th>
                                    <th class="text-center" colspan="2">Menu</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for data in table %}
                                <tr>
                                    <td>1</td>
                                    <td><img src="/media/{{data.restaurents.restaurent_pics}}" alt=""> {{data.restaurents.name }}</td>
                                    <td>
                                        <div class="badge badge-info text-center">{{ data.status }}</div>
                                    </td>
                                    <td class="text-center">
                                        <a class="btn btn-sm btn-warning"
                                            href="{% url 'Product_App:menus' id=data.restaurents.id %}">View</a>
                                        {% if data.status == 'Accepted' %}
                                        <a class="btn btn-sm btn-success" href="{% url 'Product_App:cart_detail' id=data.restaurents.id %}">Cart</a>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}