App_Login/urls.py
from django.urls import path

from App_Login import views

app_name = 'App_Login'

urlpatterns = [
     path('register/', views.register, name='register'),
     path('login/', views.login_page, name='login'),
     path('profile/', views.home, name='profile'),
     path('logout/', views.logout_user, name='logout'),
]

Product_App/urls.py
from django.urls import path

from Product_App import views

app_name = 'Product_App'

urlpatterns = [
    path('', views.index, name='index'),
    path('reservation/<int:id>', views.reservation, name='reservation'),
    path('ur_reserve/', views.ur_reserve, name='ur_reserve'),
    path('menus/<int:id>', views.menu_list, name='menus'),
    path('orders/', views.orders, name='orders'),

    # Cart
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/<int:id>', views.cart_detail, name='cart_detail'),
]

Restaurent_App/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from App_Login import views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('account/', include('App_Login.urls')),
    path('product/', include('Product_App.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Development Area</title>
	<!-- ALL CSS FILES  -->
	{% load static %}
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
</head>

<body>

	<nav class="navbar navbar-expand navbar-dark bg-dark">
		<ul class="nav navbar-nav">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'index' %}">Home</a>
			</li>
			{% if user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'Product_App:ur_reserve' %}">Reservation</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'Product_App:ur_reserve' %}">History</a>
			</li>
			<div class="nav-item dropdown">
				<a href="" class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown">
					@{{user.username}}
				</a>
				<div class="dropdown-menu">
					<a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a>
					<hr>
					<a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
				</div>
			</div>
			<li class="nav-item">
				<a href=""><i class="fa fa-shopping-cart"></i> Cart <span class="badge badge-warning">{{request.session.cart|length}}</span></a>
			</li>
			{% else %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'App_Login:register' %}">Registration</a>
			</li>
			{% endif %}
		</ul>
	</nav>

	{% block content %}

	{% endblock %}


	<!-- JS FILES  -->
	<script src="{% static 'assets/js/jquery-3.4.1.min.js' %}"></script>
	<script src="{% static 'assets/js/popper.min.js' %}"></script>
	<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'assets/js/custom.js ' %}"></script>
</body>

</html>